// object
var keyWords = {
    129: "An Ninh / Bảo Vệ",
    313: "An Ninh / Bảo Vệ&nbsp;",
    158: "An Toàn Lao Động",
    643: "An ninh-Bảo vệ",
    634: "An toàn lao động",
    339: "An toàn lao động&nbsp;",
    277: "Biên dịch/Phiên dịch",
    626: "Biên phiên dịch",
    125: "Biên phiên dịch (tiếng Nhật)",
    124: "Biên phiên dịch / Thông dịch viên",
    301: "Biên phiên dịch&nbsp;",
    493: "Biên tập/ Báo chí/ Truyền hình",
    609: "Bác sĩ",
    265: "Bán hàng",
    7: "Bán hàng / Kinh doanh",
    622: "Bán hàng kỹ thuật",
    130: "Bán lẻ / Bán sỉ",
    318: "Bán lẻ / Bán sỉ&nbsp;",
    589: "Bán lẻ/Bán sỉ",
    170: "Báo chí / Biên tập viên / Xuất bản",
    371: "Báo chí / Truyền hình",
    102: "Báo chí/Biên tập viên",
    645: "Bưu chính",
    421: "Bưu chính VT",
    103: "Bưu chính viễn thông",
    332: "Bưu chính viễn thông&nbsp;",
    586: "Bảo hiểm",
    308: "Bảo hiểm&nbsp;",
    494: "Bảo hiểm/ Tư vấn bảo hiểm",
    53: "Bảo trì / Sửa chữa",
    324: "Bảo trì / Sửa chữa&nbsp;",
    635: "Bảo trì/Sửa chữa",
    470: "Bảo vệ",
    379: "Bảo vệ / Vệ sỹ",
    495: "Bảo vệ/ An ninh/ Vệ sỹ",
    93: "Bảo vệ/Vệ sĩ/An ninh",
    245: "Bất động sản",
    295: "Bất động sản&nbsp;",
    29: "CNTT - Phần cứng / Mạng",
    150: "CNTT - Phần mềm",
    424: "CNTT/Tin học",
    484: "Chuyên viên pháp lý",
    268: "Chăm sóc khách hàng",
    65: "Chăn nuôi / Thú y",
    347: "Chăn nuôi / Thú y&nbsp;",
    401: "Chế biến",
    34: "Chứng khoán",
    498: "Chứng khoán - Vàng",
    348: "Chứng khoán&nbsp;",
    662: "Chứng khoán- Vàng",
    500: "Công chức - Viên chức",
    502: "Công nghiệp",
    606: "Công nghệ cao",
    62: "Công nghệ sinh học",
    349: "Công nghệ sinh học&nbsp;",
    239: "Công nghệ thông tin",
    402: "Công nghệ thực phẩm",
    58: "Công nghệ thực phẩm / Dinh dưỡng",
    338: "Công nghệ thực phẩm / Dinh dưỡng&nbsp;",
    466: "Công nhân/ Nhân viên",
    399: "Cơ / Điện lạnh / Điện CN",
    596: "Cơ khí",
    499: "Cơ khí - Chế tạo",
    396: "Cơ khí / Chế tạo",
    302: "Cơ khí / Ô tô / Tự động hóa&nbsp;",
    47: "Cơ khí&nbsp;/ Ô tô&nbsp;/ Tự động hóa",
    184: "Cơ khí-Chế tạo",
    427: "Cơ khí/Chế tạo máy",
    267: "Cơ khí/Kĩ thuật ứng dụng",
    638: "Cấp quản lý điều hành",
    506: "Du lịch",
    323: "Du lịch&nbsp;",
    439: "Du lịch/Khách sạn",
    240: "Du lịch/Nhà hàng/Khách sạn"
};

