<?php

class Foo {
    function Foo()
    {
        echo 'Class Foo da duoc khoi tao <br>';
    }

    function getMessage()
    {
        echo 'Day la class Foo <br>';
    }

    function __destruct()
    {
        // TODO: Implement __destruct() method.
        echo 'Class Foo da duoc huy <br>';
    }
}

class Bar extends Foo
{
    function __construct()
    {
        parent::Foo();
        echo 'Class Bar da duoc khoi tao <br>';
    }
    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
        echo 'Class Bar da duoc huy <br>';
    }
}

//$foo = new Foo();
//$foo->getMessage();


$bar = new Bar();